import type { Brand, FaultCode, BlogPost, Testimonial, Location, Service, Manual } from '@/types';

export const BRANDS: Brand[] = [
  { name: 'Hobart', slug: 'hobart', description: 'Industry-leading commercial dishwasher manufacturer trusted by professional kitchens worldwide.', seoTitle: 'Hobart Dishwasher Repair & Manuals', seoDescription: 'Expert Hobart commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Winterhalter', slug: 'winterhalter', description: 'Premium warewashing solutions for hotels, restaurants and catering operations.', seoTitle: 'Winterhalter Dishwasher Repair & Manuals', seoDescription: 'Expert Winterhalter commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Classeq', slug: 'classeq', description: 'British-made commercial glasswashers and dishwashers built for reliability.', seoTitle: 'Classeq Dishwasher Repair & Manuals', seoDescription: 'Expert Classeq commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Maidaid', slug: 'maidaid', description: 'Commercial catering equipment specialists with a focus on warewashing.', seoTitle: 'Maidaid Dishwasher Repair & Manuals', seoDescription: 'Expert Maidaid commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Meiko', slug: 'meiko', description: 'High-performance commercial warewashing solutions for demanding environments.', seoTitle: 'Meiko Dishwasher Repair & Manuals', seoDescription: 'Expert Meiko commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Electrolux', slug: 'electrolux', description: 'Professional catering equipment including commercial dishwashers and glasswashers.', seoTitle: 'Electrolux Dishwasher Repair & Manuals', seoDescription: 'Expert Electrolux commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Fagor', slug: 'fagor', description: 'Spanish manufacturer of professional kitchen and warewashing equipment.', seoTitle: 'Fagor Dishwasher Repair & Manuals', seoDescription: 'Expert Fagor commercial dishwasher repair, fault codes and manuals.' },
  { name: 'Comenda', slug: 'comenda', description: 'Italian commercial dishwasher manufacturer known for energy-efficient machines.', seoTitle: 'Comenda Dishwasher Repair & Manuals', seoDescription: 'Expert Comenda commercial dishwasher repair, fault codes and manuals.' },
];

export const SERVICES: Service[] = [
  { title: 'Commercial Dishwasher Repairs', slug: 'repairs', description: 'Fast, reliable repairs for all makes and models of commercial dishwashers.', content: 'Our engineers carry a wide range of spare parts and can diagnose and fix most faults on the first visit. We service all major brands including Hobart, Winterhalter, Classeq, and more.', seoTitle: 'Commercial Dishwasher Repair Service', seoDescription: 'Professional commercial dishwasher repair service. Fast response, 98% first-time fix rate.' },
  { title: 'Installation', slug: 'installation', description: 'Professional installation of new commercial dishwashers and glasswashers.', content: 'Our engineers install all makes and models of commercial dishwashers, ensuring correct plumbing, electrical connections, and commissioning.', seoTitle: 'Commercial Dishwasher Installation', seoDescription: 'Professional commercial dishwasher installation service by certified engineers.' },
  { title: 'Planned Maintenance', slug: 'maintenance', description: 'Preventive maintenance contracts to keep your machines running efficiently.', content: 'Regular maintenance reduces breakdowns, extends machine life, and keeps your kitchen compliant. We offer flexible maintenance contracts tailored to your needs.', seoTitle: 'Commercial Dishwasher Maintenance Contracts', seoDescription: 'Planned maintenance contracts for commercial dishwashers. Reduce breakdowns and extend machine life.' },
  { title: 'Emergency Call Outs', slug: 'emergency', description: '24/7 emergency repair service for when you need help fast.', content: 'When your dishwasher breaks down during service, every minute counts. Our 24/7 emergency call out service gets an engineer to you as quickly as possible.', seoTitle: 'Emergency Commercial Dishwasher Repair', seoDescription: '24/7 emergency commercial dishwasher repair service. Fast response across the UK.' },
];

export const FAULT_CODES: FaultCode[] = [
  { brand: 'Hobart', model: 'AM15', code: 'F1', title: 'Temperature Sensor Fault', description: 'The wash temperature sensor is not reading correctly.', commonCauses: ['Faulty temperature probe', 'Wiring fault', 'Control board issue'], recommendedActions: ['Check probe resistance', 'Inspect wiring harness', 'Replace probe if out of spec'], seoTitle: 'Hobart AM15 F1 Fault Code', seoDescription: 'Fix the Hobart AM15 F1 temperature sensor fault code.' },
  { brand: 'Winterhalter', model: 'UC-M', code: 'E2', title: 'Wash Pump Fault', description: 'The wash pump is not operating correctly.', commonCauses: ['Blocked pump', 'Capacitor failure', 'Motor winding fault'], recommendedActions: ['Clear blockage', 'Test capacitor', 'Replace pump motor'], seoTitle: 'Winterhalter UC-M E2 Fault Code', seoDescription: 'Fix the Winterhalter UC-M E2 wash pump fault code.' },
  { brand: 'Classeq', model: 'Hydro 750', code: 'C3', title: 'Drain Fault', description: 'The machine is not draining correctly within the set time.', commonCauses: ['Blocked drain filter', 'Blocked drain hose', 'Drain pump failure'], recommendedActions: ['Clean drain filter', 'Check drain hose', 'Test drain pump'], seoTitle: 'Classeq Hydro 750 C3 Fault Code', seoDescription: 'Fix the Classeq Hydro 750 C3 drain fault code.' },
];

export const MANUALS: Manual[] = [
  { title: 'Hobart AM15 User Manual', slug: 'hobart-am15-user-manual', brand: 'Hobart', model: 'AM15', productType: 'Rack Dishwasher', description: 'Complete user and installation manual for the Hobart AM15 rack dishwasher.', seoTitle: 'Hobart AM15 Manual Download', seoDescription: 'Download the Hobart AM15 commercial dishwasher user manual PDF.' },
  { title: 'Winterhalter UC-M Manual', slug: 'winterhalter-uc-m-manual', brand: 'Winterhalter', model: 'UC-M', productType: 'Undercounter Dishwasher', description: 'Full installation and operation manual for the Winterhalter UC-M.', seoTitle: 'Winterhalter UC-M Manual Download', seoDescription: 'Download the Winterhalter UC-M undercounter dishwasher manual PDF.' },
  { title: 'Classeq Hydro 750 Manual', slug: 'classeq-hydro-750-manual', brand: 'Classeq', model: 'Hydro 750', productType: 'Glasswasher', description: 'User and maintenance manual for the Classeq Hydro 750 glasswasher.', seoTitle: 'Classeq Hydro 750 Manual Download', seoDescription: 'Download the Classeq Hydro 750 glasswasher manual PDF.' },
];

export const TESTIMONIALS: Testimonial[] = [
  { customerName: 'James Hartley', companyName: 'The Grand Hotel', review: 'Excellent service from start to finish. The engineer arrived within 2 hours and had our Hobart back up and running before the lunch service. Highly recommended.', rating: 5 },
  { customerName: 'Sarah Chen', companyName: 'Chen\'s Restaurant Group', review: 'We\'ve used Advanced Dishwasher Repairs for 3 years across all our sites. Reliable, knowledgeable engineers and fair pricing. Won\'t use anyone else.', rating: 5 },
  { customerName: 'Mike Thompson', companyName: 'Thompson\'s Catering', review: 'Called at 7pm on a Friday when our machine packed up. Engineer arrived by 9pm and sorted the issue. Lifesavers! The emergency call out service is worth every penny.', rating: 5 },
  { customerName: 'Emma Davies', companyName: 'Oakwood School', review: 'Professional maintenance contract has reduced our downtime by 80%. The team are thorough, tidy and always explain what they\'ve done. Brilliant service.', rating: 5 },
];

export const BLOG_POSTS: BlogPost[] = [
  { title: '5 Signs Your Commercial Dishwasher Needs Servicing', slug: '5-signs-commercial-dishwasher-needs-servicing', excerpt: 'Spotting early warning signs can prevent costly breakdowns. Here are the top indicators that your machine needs attention.', content: '', featuredImage: undefined, author: 'Advanced Dishwasher Repairs', publishDate: '2026-06-01', seoTitle: '5 Signs Your Commercial Dishwasher Needs Servicing', seoDescription: 'Learn the early warning signs that your commercial dishwasher needs servicing before a costly breakdown occurs.' },
  { title: 'How to Reduce Commercial Dishwasher Running Costs', slug: 'reduce-commercial-dishwasher-running-costs', excerpt: 'Energy and water costs can be significant. These practical tips will help you run your machine more efficiently.', content: '', featuredImage: undefined, author: 'Advanced Dishwasher Repairs', publishDate: '2026-05-15', seoTitle: 'How to Reduce Commercial Dishwasher Running Costs', seoDescription: 'Practical tips to reduce your commercial dishwasher energy and water costs.' },
  { title: 'Choosing the Right Commercial Dishwasher for Your Business', slug: 'choosing-right-commercial-dishwasher', excerpt: 'From undercounter glasswashers to large rack machines, we guide you through selecting the right equipment.', content: '', featuredImage: undefined, author: 'Advanced Dishwasher Repairs', publishDate: '2026-05-01', seoTitle: 'Choosing the Right Commercial Dishwasher', seoDescription: 'A guide to choosing the right commercial dishwasher or glasswasher for your business.' },
];

export const LOCATIONS: Location[] = [
  { name: 'London', slug: 'london', content: 'We provide commercial dishwasher repair services across all London boroughs.', coverageArea: 'All London postcodes', seoTitle: 'Commercial Dishwasher Repair London', seoDescription: 'Fast commercial dishwasher repair service across London. Same-day call outs available.' },
  { name: 'Manchester', slug: 'manchester', content: 'Covering Greater Manchester and surrounding areas for commercial dishwasher repairs.', coverageArea: 'Greater Manchester', seoTitle: 'Commercial Dishwasher Repair Manchester', seoDescription: 'Expert commercial dishwasher repair service in Manchester. Fast response.' },
  { name: 'Birmingham', slug: 'birmingham', content: 'Commercial dishwasher repair and maintenance across Birmingham and the West Midlands.', coverageArea: 'Birmingham and West Midlands', seoTitle: 'Commercial Dishwasher Repair Birmingham', seoDescription: 'Professional commercial dishwasher repair in Birmingham. 24/7 emergency call outs.' },
  { name: 'Leeds', slug: 'leeds', content: 'Serving Leeds and West Yorkshire with expert commercial dishwasher repairs.', coverageArea: 'Leeds and West Yorkshire', seoTitle: 'Commercial Dishwasher Repair Leeds', seoDescription: 'Reliable commercial dishwasher repair service in Leeds and West Yorkshire.' },
];
